const constants = {
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  ADD_ERROR: "ADD_ERROR",
  DELETE_ERROR: "DELETE_ERROR",
  TOGGLE_LOADING: "TOGGLE_LOADING",
};

export default constants;
