const constants = {
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  SELECT_USER: "SELECT_USER",
  SELECT_USERS: "SELECT_USERS",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  ADD_LOADING: "ADD_LOADING",
  CLEAR_LOADING: "CLEAR_LOADING",
};

export default constants;
