const list = [
  {
    line: 7,
    direction: "Northbound",
    video: "https://youtu.be/-vRrQ_gT_yk?t=32",
  },
  {
    line: 7,
    direction: "Southbound",
    video: "https://youtu.be/KmCeOvBMEbs?t=21",
  },
  {
    line: 8,
    direction: "Northbound",
    video: "https://youtu.be/qqqCx1ITSz8?t=75",
  },
  {
    line: 8,
    direction: "Southbound",
    video: "https://youtu.be/32k-GPWVR9w?t=1",
  },
  {
    line: 9,
    direction: "Northbound",
    video: "https://youtu.be/MeP170iavig?t=78",
  },
  { line: 9, direction: "Southbound", video: "https://youtu.be/7IMUYTrC3YU" },
  {
    line: 10,
    direction: "Eastbound",
    video: "https://youtu.be/l74av8ThELU?t=32",
  },
  {
    line: 10,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 11,
    direction: "Northbound",
    video: "https://youtu.be/4LE4fia4914?t=36",
  },
  {
    line: 11,
    direction: "Southbound",
    video: "https://youtu.be/Q3hSw87VH1E?t=31",
  },
  {
    line: 12,
    direction: "Eastbound",
    video: "https://youtu.be/SIQ7uU44xtc?t=15",
  },
  {
    line: 12,
    direction: "Westbound",
    video: "https://youtu.be/JyepkjcU7fg?t=22",
  },
  {
    line: 13,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 13,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 14,
    direction: "Eastbound",
    video: "https://youtu.be/2fPmFemKvUQ?t=22",
  },
  {
    line: 14,
    direction: "Westbound",
    video: "https://youtu.be/80eOvnRRv-8?t=26",
  },
  {
    line: 15,
    direction: "Eastbound",
    video: "https://youtu.be/-0mT4jhn5v8?t=36",
  },
  {
    line: 15,
    direction: "Westbound",
    video: "https://youtu.be/bSQYWhwZ-jE?t=17",
  },
  {
    line: 16,
    direction: "Northbound",
    video: "https://youtu.be/QcnEdgjcAfw?t=33",
  },
  {
    line: 16,
    direction: "Southbound",
    video: "https://youtu.be/XNoqknnhNGI?t=15",
  },
  {
    line: 17,
    direction: "Northbound",
    video: "https://youtu.be/VtXh-EwvrJA?t=32",
  },
  {
    line: 17,
    direction: "Southbound",
    video: "https://youtu.be/5IGJn0meOAk?t=33",
  },
  {
    line: 19,
    direction: "Northbound",
    video: "https://youtu.be/8U4D8o1Xufw",
  },
  {
    line: 19,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 20,
    direction: "Eastbound",
    video: "https://youtu.be/HQjclNNNShs?t=23",
  },
  {
    line: 20,
    direction: "Westbound",
    video: "https://youtu.be/CP3CLjDQiDY?t=30",
  },
  {
    line: 21,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 21,
    direction: "Southbound",
    video: "https://youtu.be/0jRkdXgeqqw?t=76",
  },
  { line: 22, direction: "Northbound", video: "https://youtu.be/BnhVG3HlDK4" },
  {
    line: 22,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 23,
    direction: "Northbound",
    video: "https://youtu.be/I2UVKVWdb1M?t=31",
  },
  {
    line: 23,
    direction: "Southbound",
    video: "https://youtu.be/JwCbnhYN_fU?t=77",
  },
  {
    line: 24,
    direction: "Northbound",
    video: "https://youtu.be/lyzL-dP2jqg?t=22",
  },
  { line: 24, direction: "Southbound", video: "https://youtu.be/wTU4bFeohYo" },
  {
    line: 25,
    direction: "Northbound",
    video: "https://youtu.be/Rqd5J0ae0XQ?t=33",
  },
  { line: 25, direction: "Southbound", video: "https://youtu.be/wK7I3Oa-Boo" },
  {
    line: 26,
    direction: "Eastbound",
    video: "https://youtu.be/O81Ju6ZqMI4?t=12",
  },
  {
    line: 26,
    direction: "Westbound",
    video: "https://youtu.be/GLBPIV2tVEo?t=21",
  },
  {
    line: 28,
    direction: "Eastbound",
    video: "https://youtu.be/aJc6hD0aiQE",
  },
  {
    line: 28,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
    disabled: true,
  },
  {
    line: 29,
    direction: "Northbound",
    video: "https://youtu.be/XPqv2JxYqs4?t=75",
  },
  { line: 29, direction: "Southbound", video: "https://youtu.be/RxOW5eKDf5s" },
  { line: 30, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 30, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 31, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 31, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 32, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 32, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 33, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 33, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 34, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 34, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 35, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 35, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 36, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 36, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 37, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 37, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 38, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 38, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 39, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 39, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 40, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 40, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 41, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 41, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 42, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 42, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 43, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 43, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 44, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 44, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 45, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 45, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 46, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 46, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 47, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 47, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 48, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 48, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 49, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 49, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 50, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 50, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 51, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 51, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 52, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 52, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 53, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 53, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 54, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 54, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 55, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 55, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 56, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 56, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 57, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 57, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 59, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 59, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 60, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 60, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 61, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 61, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 62, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 62, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 63, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 63, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 64, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 64, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 65, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 65, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 66, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 66, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 67, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 67, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 68, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 68, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 69, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 69, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 70, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 70, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 71, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 71, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 72, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 72, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 73, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 73, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 74, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 74, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 75, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 75, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 76, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 76, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 77, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 77, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 78, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 78, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 79, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 79, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 80, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 80, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 81, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 81, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 82, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 82, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 83, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 83, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 84, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 84, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 85, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 85, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 86, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 86, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 87, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 87, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 88, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 88, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 89, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 89, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 90, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 90, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 91, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 91, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 92, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 92, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 93, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 93, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 94, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 94, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 95, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 95, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 96, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 96, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 97, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 97, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 98, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 98, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 99, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 99, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 100, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 100, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 101, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 101, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 102, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 102, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 104, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 104, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 105, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 105, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 106, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 106, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 107, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 107, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 108, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 108, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 109, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 109, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 110, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 110, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 111, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 111, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 112, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 112, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 113, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 113, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 115, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 115, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 116, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 116, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 117, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 117, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 118, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 118, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 119, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 119, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 120, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 120, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 121, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 121, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 122, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 122, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 123, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 123, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 124, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 124, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 125, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 125, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 126, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 126, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 127, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 127, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 129, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 129, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 130, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 130, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 131, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 131, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 132, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 132, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 133, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 133, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 134, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 134, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 135, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 135, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 160, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 160, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 161, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 161, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 162, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 162, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 165, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 165, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 167, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 167, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 168, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 168, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 169, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 169, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 171, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 171, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 175, direction: "Northbound", video: "https://youtu.be/test?t=35" },
  { line: 175, direction: "Southbound", video: "https://youtu.be/test?t=35" },
  { line: 176, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 176, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  { line: 189, direction: "Eastbound", video: "https://youtu.be/test?t=35" },
  { line: 189, direction: "Westbound", video: "https://youtu.be/test?t=35" },
  {
    type: "express",
    line: 900,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 900,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 902,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 902,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 903,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 903,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 905,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 905,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 913,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 913,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 924,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 924,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 925,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 925,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 927,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 927,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 929,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 929,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 935,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 935,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 937,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 937,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 939,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 939,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 941,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 941,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 944,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 944,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 945,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 945,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 952,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 952,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 953,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 953,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 954,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 954,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 960,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 960,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 984,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 984,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 985,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 985,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 986,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 986,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 989,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 989,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 995,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 995,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 996,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "express",
    line: 996,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 141,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 141,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 142,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 142,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 143,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 143,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 144,
    direction: "Northbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 144,
    direction: "Southbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 145,
    direction: "Eastbound",
    video: "https://youtu.be/test?t=35",
  },
  {
    type: "dt",
    line: 145,
    direction: "Westbound",
    video: "https://youtu.be/test?t=35",
  },
];

export default list;
